DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS SLOT;

CREATE TABLE USER
(
ID INT PRIMARY KEY AUTO_INCREMENT,
USER_EMAIL VARCHAR NOT NULL UNIQUE,
USER_NAME VARCHAR NOT NULL,
HASHED_PASSWORD VARCHAR NOT NULL,
SALT VARCHAR NOT NULL
);

CREATE TABLE SLOT
(
USER_ID_OWNER INT NOT NULL,
SLOT_START TIMESTAMP NOT NULL,
STATUS BOOLEAN NOT NULL DEFAULT TRUE,
USER_ID_BOOKED_BY INT NOT NULL,
FOREIGN KEY (USER_ID_OWNER) REFERENCES USER(ID),
FOREIGN KEY (USER_ID_BOOKED_BY) REFERENCES USER(ID)
);

insert into user (USER_EMAIL, USER_NAME, HASHED_PASSWORD, SALT) values ('zafar@google.com', 'Zafar', 'zafa@123', 'qwerty');